### ISSUE TITLE
use consts for permissions to avoid typo problems

### ISSUE THREAD

**Issue by jgcmarins** [jean-leonco/manbu-mono#10]
check this:
- https://github.com/jean-leonco/manbu-mono/blob/a1e52f6e9696778d22511079723413cd175eaec5/packages/server/src/modules/sale/mutations/DeleteSale.ts#L47
- https://github.com/jean-leonco/manbu-mono/blob/a1e52f6e9696778d22511079723413cd175eaec5/packages/server/src/modules/user/mutations/UserRegistrationMutation.ts#L33-L38

**Comment by jean-leonco** [comment]
closing due to the merge of PR #25
